#! /usr/bin/env python3

import http.client
import json
import os
import sys


auth_email_env_name = 'CLOUDFLARE_EMAIL'
auth_key_env_name = 'CLOUDFLARE_API_KEY'
zone_id_env_name = 'CLOUDFLARE_JEFFREYPRATTNET_ZONE_ID'

auth_email = os.getenv(auth_email_env_name)
auth_key = os.getenv(auth_key_env_name)
zone_id = os.getenv(zone_id_env_name)

if not auth_email:
    print(f"Auth email is required. Set {auth_email_env_name}.", file=sys.stderr)
if not auth_key:
    print(f"Auth key is required. Set {auth_key_env_name}.", file=sys.stderr)
if not zone_id:
    print(f"Zone ID is required. Set {zone_id_env_name}.", file=sys.stderr)

if not auth_email or not auth_key or not zone_id:
    sys.exit(1)

conn = http.client.HTTPSConnection("api.cloudflare.com")

headers = {
    'Content-Type': "application/json",
    'X-Auth-Email': auth_email,
    'X-Auth-Key': auth_key
}

payload = {
    'purge_everything': True
}

conn.request("POST", f"/client/v4/zones/{zone_id}/purge_cache", json.dumps(payload), headers)
res = conn.getresponse()
data = res.read()

result = json.loads(data.decode("utf-8"))

if result['success']:
    print(f"Cache purged for {zone_id}")
else:
    for err in result['errors']:
        print(f"Error {err['code']}: {err['message']}", file=sys.stderr)
    sys.exit(1)
